import type { StackforgeConfig } from '../types/config.js';

function formatDb(config: StackforgeConfig): string {
  if (config.database.provider === 'none') return 'none';
  return `${config.database.provider}${config.database.orm ? ` (${config.database.orm})` : ''}`;
}

function getDevCommand(config: StackforgeConfig): string {
  if (config.frontend.type === 'vite' && (config.api.type === 'rest' || config.api.type === 'graphql')) {
    return 'npm run dev (frontend) + npm run api:dev (API)';
  }
  return 'npm run dev';
}

function formatFeatures(config: StackforgeConfig): string {
  if (!config.features || config.features.length === 0) return 'none';
  return config.features.join(', ');
}

export function buildProjectReadme(config: StackforgeConfig): string {
  const featureLinks = config.features
    .map((f) => `- features/${f}/README.md`)
    .join('\n');

  return `# ${config.projectName}

Generated by StackForge.

## Stack
- Frontend: ${config.frontend.type} (${config.frontend.language})
- UI: ${config.ui.library}
- Database: ${formatDb(config)}
- Auth: ${config.auth.provider}
- API: ${config.api.type}
- Features: ${formatFeatures(config)}

## Commands
- Install: ${config.packageManager} install
- Dev: ${getDevCommand(config)}

${config.features.length ? `## Feature Docs\n${featureLinks}\n` : ''}
## Notes
- Update .env values before running in production.
`;
}