import type { StackforgeConfig } from '../types/config.js';

function formatDb(config: StackforgeConfig): string {
  if (config.database.provider === 'none') return 'none';
  return `${config.database.provider}${config.database.orm ? ` (${config.database.orm})` : ''}`;
}

function getDevCommand(config: StackforgeConfig): string {
  if (config.frontend.type === 'vite' && (config.api.type === 'rest' || config.api.type === 'graphql')) {
    return 'npm run dev (frontend) + npm run api:dev (API)';
  }
  return 'npm run dev';
}

function formatFeatures(config: StackforgeConfig): string {
  const features = [];
  if (config.features.email) features.push(`email (${config.features.email})`);
  if (config.features.storage) features.push(`storage (${config.features.storage})`);
  if (config.features.payments) features.push(`payments (${config.features.payments})`);
  if (config.features.analytics) features.push(`analytics (${config.features.analytics})`);
  if (config.features.errorTracking) features.push(`error-tracking (${config.features.errorTracking})`);
  return features.length ? features.join(', ') : 'none';
}

export function buildProjectReadme(config: StackforgeConfig): string {
  const featureCategories = [];
  if (config.features.email) featureCategories.push('email');
  if (config.features.storage) featureCategories.push('storage');
  if (config.features.payments) featureCategories.push('payments');
  if (config.features.analytics) featureCategories.push('analytics');
  if (config.features.errorTracking) featureCategories.push('error-tracking');

  const featureLinks = featureCategories
    .map((f) => `- features/${f}/README.md`)
    .join('\n');

  return `# ${config.projectName}

Generated by StackForge.

## Stack
- Frontend: ${config.frontend.type} (${config.frontend.language})
- UI: ${config.ui.library}
- Database: ${formatDb(config)}
- Auth: ${config.auth.provider}
- API: ${config.api.type}
- Features: ${formatFeatures(config)}

## Commands
- Install: ${config.packageManager} install
- Dev: ${getDevCommand(config)}

${featureCategories.length ? `## Feature Docs\n${featureLinks}\n` : ''}
## Notes
- Update .env values before running in production.
`;
}